---

- name: Create nginx directories
  ansible.builtin.file:
    path: "{{ item | regex_replace(':.*') }}"
    state: directory
    owner: root
    group: "{{ nginx_proxy_docker_group | default('root') }}"
    mode: "0755"
  loop: "{{ nginx_docker_volumes }}"
  when: item is search(':')

- name: Create nginx configuration
  ansible.builtin.template:
    src: nginx.vhost.conf.j2
    dest: "{{ nginx_confd_path }}/{{ vhost.fqdn }}.conf"
    mode: "0644"
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost

- name: Create nginx_proxy/nginx configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: docker-compose.yml.j2
      dest: "{{ nginx_root_path }}/docker-compose.yml"
  notify: Restart docker

- name: Create SSL certificate (self-signed)
  ansible.builtin.include_role:
    name: deitkrachten.openssl
  vars:
    openssl_server_key: "{{ nginx_certs_path }}/{{ nginx_fqdn }}.key"
    openssl_server_crt: "{{ nginx_certs_path }}/{{ nginx_fqdn }}.crt"
    openssl_server_csr: "{{ nginx_certs_path }}/{{ nginx_fqdn }}.csr"
    openssl_type: self-signed
  args:
    apply:
      become: yes
  when: nginx_cert_type == 'self-signed'
