---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    nginx_docker_environment: []
    nginx_docker_networks: []
  tasks:
    - name: Include role 'ansible-role-nginx_docker'
      ansible.builtin.include_role:
        name: ansible-role-nginx_docker
